global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "trustledger-demo"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["demo:8080"]
        labels:
          subsystem: "demo-gateway"

  - job_name: "trustledger-raft-nodes"
    static_configs:
      - targets: ["raft-node-1:50051", "raft-node-2:50052", "raft-node-3:50053"]
        labels:
          cluster: "trustledger-raft"
