//! Synthetic financial workload generator for the simulator.
//!
//! It exercises direct transfers, holds, captures, and cancellations across a
//! configured account pool.

use std::collections::BTreeMap;

use crate::rng::SimRng;

/// A discrete financial operation generated by the simulation workload.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum WorkloadOp {
    /// Immediate settlement transfer from payer to payee.
    DirectTransfer {
        /// Unique transfer identifier.
        transfer_id: u128,
        /// Source debit account.
        from: u128,
        /// Destination credit account.
        to: u128,
        /// Transfer amount in base units.
        amount: u128,
    },
    /// Two-phase authorization hold placing funds in escrow.
    CreatePending {
        /// Unique hold identifier.
        transfer_id: u128,
        /// Source debit account.
        from: u128,
        /// Destination credit account.
        to: u128,
        /// Reserved hold amount in base units.
        amount: u128,
    },
    /// Capture/execution of an authorized hold.
    PostPending {
        /// Existing pending hold identifier.
        pending_id: u128,
        /// Final posted transfer identifier.
        post_id: u128,
        /// Settled capture amount.
        amount: u128,
    },
    /// Cancellation/release of an authorized hold.
    VoidPending {
        /// Existing pending hold identifier.
        pending_id: u128,
        /// Final void transfer identifier.
        void_id: u128,
    },
}

/// Generator synthesizing continuous payment operations across defined accounts.
#[derive(Debug, Clone)]
pub struct WorkloadGenerator {
    accounts: Vec<u128>,
    active_holds: BTreeMap<u128, (u128, u128, u128)>,
    next_transfer_id: u64,
}

impl WorkloadGenerator {
    /// Creates a new workload generator over the specified account pool.
    #[must_use]
    pub fn new(accounts: Vec<u128>, initial_transfer_id: u64) -> Self {
        Self {
            accounts,
            active_holds: BTreeMap::new(),
            next_transfer_id: initial_transfer_id,
        }
    }

    /// Generates the next pseudo-random financial operation according to realistic fintech ratios.
    pub fn next_op(&mut self, rng: &mut SimRng) -> WorkloadOp {
        if !self.active_holds.is_empty() && rng.gen_bool(0.35) {
            let keys: Vec<u128> = self.active_holds.keys().copied().collect();
            if let Some(&pending_id) = rng.choose(&keys) {
                if let Some((_from, _to, amount)) = self.active_holds.remove(&pending_id) {
                    self.next_transfer_id = self.next_transfer_id.saturating_add(1);
                    let next_id = u128::from(self.next_transfer_id);

                    if rng.gen_bool(0.75) {
                        return WorkloadOp::PostPending {
                            pending_id,
                            post_id: next_id,
                            amount,
                        };
                    }
                    return WorkloadOp::VoidPending {
                        pending_id,
                        void_id: next_id,
                    };
                }
            }
        }

        let num_accounts = self.accounts.len().max(2);
        let from_idx = (rng.gen_range(0..self.accounts.len() as u64) as usize) % num_accounts;
        let mut to_idx = (rng.gen_range(0..self.accounts.len() as u64) as usize) % num_accounts;
        while to_idx == from_idx && self.accounts.len() > 1 {
            to_idx = (rng.gen_range(0..self.accounts.len() as u64) as usize) % num_accounts;
        }

        let from = self.accounts.get(from_idx).copied().unwrap_or(0);
        let to = self.accounts.get(to_idx).copied().unwrap_or(1);
        let amount = u128::from(rng.gen_range(10..=500));

        self.next_transfer_id = self.next_transfer_id.saturating_add(1);
        let transfer_id = u128::from(self.next_transfer_id);

        if rng.gen_bool(0.50) {
            self.active_holds.insert(transfer_id, (from, to, amount));
            WorkloadOp::CreatePending {
                transfer_id,
                from,
                to,
                amount,
            }
        } else {
            WorkloadOp::DirectTransfer {
                transfer_id,
                from,
                to,
                amount,
            }
        }
    }

    /// Returns the number of currently outstanding authorization holds.
    #[must_use]
    pub fn active_holds_count(&self) -> usize {
        self.active_holds.len()
    }
}
